name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Adjust this if your main branch is not master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${ACTIONS_DEPLOY_KEY}" > ~/.ssh/github_actions_deploy_key
          chmod 600 ~/.ssh/github_actions_deploy_key
          ls -la ~/.ssh
          cat ~/.ssh/github_actions_deploy_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin git@github.com:07UPENDRA/my-app.git
          ssh -T git@github.com
          npm run deploy
